"""Generate the Zig source ownership map from source-layout.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "source-layout.json"
OUTPUT_PATH = ROOT / "src" / "README.md"


def render_source_map(config: dict[str, Any]) -> str:
    owners = "\n".join(
        f"| `{name}/` | {description} |"
        for name, description in sorted(config["topLevelOwners"].items())
    )
    wgsl_stages = "\n".join(
        f"  {name}/" for name in config["wgslStageDirectories"]
    )
    compatibility = "\n".join(
        f"- `{path}`" for path in config["compatibilityFacades"]
    )
    repository_roots = ", ".join(
        f"`../{path}/`" for path in config["repositoryOnlyZigRoots"]
    )
    module_root = Path(config["moduleRoot"]).name
    return f"""<!-- Generated by tools/generate_source_layout_docs.py. -->
# Doe Zig source map

Production source is organized by ownership boundary. `{module_root}`
is the single module root; every other Zig file belongs to one owner below.

| Directory | Owns |
| --- | --- |
{owners}

WGSL follows the compiler-stage directories declared by `source-layout.json`:

```text
compiler/wgsl/
{wgsl_stages}
```

Repository-only Zig roots live outside production `src/`: {repository_roots}.
`source-layout.json` and `tools/check_source_layout.py` enforce the map.

Declared compatibility facades:

{compatibility}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    rendered = render_source_map(config)
    if args.write:
        OUTPUT_PATH.write_text(rendered, encoding="utf-8")
        return 0
    if OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
        print(
            "generated source map is stale; run "
            "python3 tools/generate_source_layout_docs.py --write"
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
