"""Generate pinned WebGPU ABI aliases and loader metadata."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = ROOT.parents[1]
POLICY_PATH = REPOSITORY_ROOT / "config" / "webgpu-abi-source.json"
SYMBOL_PATH = REPOSITORY_ROOT / "config" / "dropin_abi.symbols.txt"
OUTPUT_PATH = ROOT / "src" / "core" / "abi" / "generated" / "webgpu_upstream.zig"

ZIG_DECLARATION = re.compile(
    r"^pub\s+const\s+(WGPU[A-Za-z0-9_]+)\s*=\s*(.+)$", re.MULTILINE
)
HEADER_NAME = re.compile(r"\b(WGPU[A-Za-z0-9_]+)\b")
HEADER_PROC = re.compile(r"\b(wgpu[A-Za-z0-9_]+)\s*\(")
FEATURE_NAME = re.compile(r"\b(WGPUFeatureName_[A-Za-z0-9_]+)\b")
MANUAL_PREFIXES = (
    "enum",
    "extern struct",
    "opaque",
    "u8",
    "u16",
    "u32",
    "u64",
    "i8",
    "i16",
    "i32",
    "i64",
    "?*anyopaque",
    "*anyopaque",
    "*const fn",
)
REQUIRED_ALIAS_NAMES = {
    "WGPUBackendType",
    "WGPUCallbackMode",
    "WGPUComponentSwizzle",
    "WGPUDeviceLostCallback",
    "WGPUDeviceLostCallbackInfo",
    "WGPUDeviceLostReason",
    "WGPUErrorType",
    "WGPUFeatureLevel",
    "WGPUPowerPreference",
    "WGPUQueueWorkDoneCallback",
    "WGPUQueueWorkDoneCallbackInfo",
    "WGPUQueueWorkDoneStatus",
    "WGPURenderPassMaxDrawCount",
    "WGPURequestAdapterCallback",
    "WGPURequestAdapterCallbackInfo",
    "WGPURequestAdapterStatus",
    "WGPURequestDeviceCallback",
    "WGPURequestDeviceCallbackInfo",
    "WGPURequestDeviceStatus",
    "WGPUTextureComponentSwizzle",
    "WGPUTextureComponentSwizzleDescriptor",
    "WGPUUncapturedErrorCallback",
    "WGPUUncapturedErrorCallbackInfo",
    "WGPUWaitStatus",
}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _symbol_contract(path: Path) -> list[str]:
    return sorted(
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )


def _alias_names(root: Path, header_names: set[str]) -> list[str]:
    names: set[str] = set()
    for path in sorted((root / "src" / "core" / "abi").rglob("*.zig")):
        if path.resolve() == OUTPUT_PATH.resolve():
            continue
        source = path.read_text(encoding="utf-8")
        for name, expression in ZIG_DECLARATION.findall(source):
            expression = expression.strip()
            if name in header_names and (
                expression.startswith(MANUAL_PREFIXES)
                or expression.startswith("upstream.")
            ):
                names.add(name)
    return sorted(names)


def _proc_type_name(proc_name: str) -> str:
    if not proc_name.startswith("wgpu") or len(proc_name) == 4:
        raise ValueError(f"invalid WebGPU procedure name: {proc_name}")
    return "WGPUProc" + proc_name[4].upper() + proc_name[5:]


def generate(root: Path, policy_path: Path, symbol_path: Path) -> str:
    policy = json.loads(policy_path.read_text(encoding="utf-8"))
    header_path = REPOSITORY_ROOT / policy["source"]["path"]
    if _sha256(header_path) != policy["source"]["sha256"]:
        raise ValueError(f"pinned header hash mismatch: {header_path}")
    header = header_path.read_text(encoding="utf-8")
    header_names = set(HEADER_NAME.findall(header))
    header_procs = set(HEADER_PROC.findall(header))
    aliases = _alias_names(root, header_names)
    missing_required_aliases = sorted(REQUIRED_ALIAS_NAMES - header_names)
    if missing_required_aliases:
        raise ValueError(
            "required ABI aliases absent from pinned header: "
            + ", ".join(missing_required_aliases)
        )
    aliases = sorted(set(aliases) | REQUIRED_ALIAS_NAMES)
    procs = _symbol_contract(symbol_path)
    missing_procs = sorted(set(procs) - header_procs)
    if missing_procs:
        raise ValueError(
            "symbol contract entries absent from pinned header: "
            + ", ".join(missing_procs)
        )
    proc_types = {name: _proc_type_name(name) for name in procs}
    missing_proc_types = sorted(
        type_name for type_name in proc_types.values() if type_name not in header_names
    )
    if missing_proc_types:
        raise ValueError(
            "procedure typedefs absent from pinned header: "
            + ", ".join(missing_proc_types)
        )
    features = sorted(set(FEATURE_NAME.findall(header)))

    lines = [
        "// Generated by tools/generate_webgpu_abi.py.",
        "// Source: config/webgpu-abi-source.json and the pinned webgpu.h.",
        "// Do not edit this file directly.",
        "",
        "pub const c = @cImport({",
        '    @cInclude("webgpu.h");',
        "});",
        "",
    ]
    lines.extend(f"pub const {name} = c.{name};" for name in aliases)
    lines.extend(
        [
            "",
            "pub const proc_names = [_][]const u8{",
            *(f'    "{name}",' for name in procs),
            "};",
            "",
            "pub const feature_names = [_][]const u8{",
            *(f'    "{name}",' for name in features),
            "};",
            "",
            "pub const ProcTypes = struct {",
            *(f"    pub const {name} = c.{proc_types[name]};" for name in procs),
            "};",
            "",
            "pub const ProcTable = extern struct {",
            *(f"    {name}: c.{proc_types[name]}," for name in procs),
            "};",
            "",
            "pub const LoaderEntry = struct {",
            "    name: []const u8,",
            "    offset: usize,",
            "};",
            "",
            "pub const loader_metadata = [_]LoaderEntry{",
            *(
                f'    .{{ .name = "{name}", .offset = @offsetOf(ProcTable, "{name}") }},'
                for name in procs
            ),
            "};",
            "",
            "comptime {",
            *(f"    _ = {name};" for name in aliases),
            "    _ = ProcTypes;",
            "    _ = ProcTable;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help="runtime/zig root")
    parser.add_argument(
        "--policy", type=Path, default=POLICY_PATH, help="ABI source policy"
    )
    parser.add_argument(
        "--symbols", type=Path, default=SYMBOL_PATH, help="drop-in symbol contract"
    )
    parser.add_argument(
        "--output", type=Path, default=OUTPUT_PATH, help="generated Zig output"
    )
    parser.add_argument(
        "--check", action="store_true", help="fail when generated output is stale"
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        rendered = generate(
            args.root.resolve(), args.policy.resolve(), args.symbols.resolve()
        )
    except (KeyError, OSError, ValueError) as exc:
        print(f"WebGPU ABI generation failed: {exc}", file=sys.stderr)
        return 1
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            print(
                f"generated WebGPU ABI is stale: run {Path(__file__).name}",
                file=sys.stderr,
            )
            return 1
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
