// Generated by doe_wgsl/emit_hlsl.zig
uint doe_atomicLoad(inout uint value) { uint result; InterlockedOr(value, 0u, result); return result; }
void doe_atomicStore(inout uint value, uint next) { uint ignored; InterlockedExchange(value, next, ignored); }
uint doe_atomicAdd(inout uint v, uint a) { uint r; InterlockedAdd(v, a, r); return r; }
uint doe_atomicSub(inout uint v, uint a) { uint r; InterlockedAdd(v, 0u - a, r); return r; }
uint doe_atomicMin(inout uint v, uint a) { uint r; InterlockedMin(v, a, r); return r; }
uint doe_atomicMax(inout uint v, uint a) { uint r; InterlockedMax(v, a, r); return r; }
uint doe_atomicAnd(inout uint v, uint a) { uint r; InterlockedAnd(v, a, r); return r; }
uint doe_atomicOr(inout uint v, uint a) { uint r; InterlockedOr(v, a, r); return r; }
uint doe_atomicXor(inout uint v, uint a) { uint r; InterlockedXor(v, a, r); return r; }
uint doe_atomicExchange(inout uint v, uint a) { uint r; InterlockedExchange(v, a, r); return r; }
int doe_atomicLoad(inout int value) { int result; InterlockedOr(value, 0, result); return result; }
void doe_atomicStore(inout int value, int next) { int ignored; InterlockedExchange(value, next, ignored); }
int doe_atomicAdd(inout int v, int a) { int r; InterlockedAdd(v, a, r); return r; }
int doe_atomicSub(inout int v, int a) { int r; InterlockedAdd(v, -a, r); return r; }
int doe_atomicMin(inout int v, int a) { int r; InterlockedMin(v, a, r); return r; }
int doe_atomicMax(inout int v, int a) { int r; InterlockedMax(v, a, r); return r; }
int doe_atomicAnd(inout int v, int a) { int r; InterlockedAnd(v, a, r); return r; }
int doe_atomicOr(inout int v, int a) { int r; InterlockedOr(v, a, r); return r; }
int doe_atomicXor(inout int v, int a) { int r; InterlockedXor(v, a, r); return r; }
int doe_atomicExchange(inout int v, int a) { int r; InterlockedExchange(v, a, r); return r; }
float2 doe_unpack2x16float(uint v) { return float2(f16tof32(v & 0xFFFFu), f16tof32(v >> 16u)); }
uint doe_pack2x16float(float2 v) { return f32tof16(v.x) | (f32tof16(v.y) << 16u); }
float4 doe_unpack4x8unorm(uint v) { return float4(v & 0xFFu, (v >> 8u) & 0xFFu, (v >> 16u) & 0xFFu, v >> 24u) / 255.0; }
float4 doe_unpack4x8snorm(uint v) { int4 s = int4(int(v << 24u) >> 24, int(v << 16u) >> 24, int(v << 8u) >> 24, int(v) >> 24); return clamp(float4(s) / 127.0, -1.0, 1.0); }
uint doe_pack4x8unorm(float4 v) { uint4 c = uint4(round(saturate(v) * 255.0)); return c.x | (c.y << 8u) | (c.z << 16u) | (c.w << 24u); }
uint doe_pack4x8snorm(float4 v) { int4 c = int4(round(clamp(v, -1.0, 1.0) * 127.0)); uint4 b = uint4(c) & 0xFFu; return b.x | (b.y << 8u) | (b.z << 16u) | (b.w << 24u); }

struct Uniforms {
    uint size;
    uint _pad0;
    uint _pad1;
    uint _pad2;
};

cbuffer doe_uniform_u : register(b0, space0) {
    Uniforms u;
};

StructuredBuffer<float> input : register(t1, space0);

RWStructuredBuffer<float> output : register(u2, space0);

uint doe_arrayLength_input() {
    uint count = 0u;
    uint stride = 0u;
    input.GetDimensions(count, stride);
    return count;
}

uint doe_arrayLength_output() {
    uint count = 0u;
    uint stride = 0u;
    output.GetDimensions(count, stride);
    return count;
}

float gelu(float x) {
    const float inner = (0.7978845608 * (x + (((0.044715 * x) * x) * x)));
    const float inner_clamped = clamp(inner, (-15.0), 15.0);
    return ((0.5 * x) * (1.0 + tanh(inner_clamped)));
}

[numthreads(256, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint idx = gid.x;
    if ((idx >= u.size)) {
        return;
    }
    const float x = input[min(idx, (doe_arrayLength_input() - 1))];
    if (idx < doe_arrayLength_output()) {
        output[min(idx, (doe_arrayLength_output() - 1))] = gelu(x);
    }
}
